### ISSUE TITLE
Hip xz motion doesnt get transferred to root bone

### ISSUE THREAD

**Issue by emberlightstudios** [RichardPerry/Mixamo-Root#7]
It adds a root bone and it adds 3 keyframes only on that bone, and the interpolation on those keys is set to Bezier not linear, as it is on the hips bone.

I tried debugging it but blender scripting is hard to understand for me.

![image](https://github.com/RichardPerry/Mixamo-Root/assets/28244273/ff2fe85f-1f98-4e59-83b4-c49d62b5682b)

**Comment by emberlightstudios** [comment]
My mistake.  I'm using FinePointCGI's fork of your code, not yours

**Comment by TheRealFame** [comment]
Nope, Not doing it here either. (Even after setup)
![image](https://github.com/RichardPerry/Mixamo-Root/assets/29516927/73978f65-e82f-4ad8-b45e-723f30192660)
